languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "confidence.sh"
description = "A blog by Confidence Okoghenun"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "January 2, 2006"

[params]
# mainSections = ["section1", "section2"]

[author]
bio = "Software Engineer & Dev Advocate from Lagos ðŸ‡³ðŸ‡¬ â€¢ I can help you learn WebAssembly. Let's connect!"
name = "Confidence Okoghenun"
image = "img/author.webp"
headline = "Software Engineer & Dev Advocate from Lagos ðŸ‡³ðŸ‡¬ â€¢ I can help you learn WebAssembly. Let's connect!"
links = [
    { youtube = "https://youtube.com/megaconfidence" },
    { github = "https://github.com/megaconfidence" },
    { twitter = "https://twitter.com/megaconfidence" },
    { linkedin = "https://linkedin.com/in/megaconfidence" },
]
