languageCode = "en"
languageName = "English"
weight = 1

title = "confidence.sh"
# copyright = "Copy, _right?_ :thinking_face:"


[params]
rtl = false
isoCode = "en"
displayName = "EN"
dateFormat = "January 2, 2006"
description = "A blog by Confidence Okoghenun"
# mainSections = ["section1", "section2"]

[author]
bio = "Software Engineer ğŸ› ï¸ â€¢ Developer Advocate ğŸ¥‘"
name = "Confidence Okoghenun"
image = "img/author.jpg"
headline = "Software Engineer ğŸ› ï¸ â€¢ Developer Advocate ğŸ¥‘"
links = [
    { youtube = "https://www.youtube.com/@megaconfidence" },
    { github = "https://github.com/megaconfidence" },
    { twitter = "https://twitter.com/megaconfidence" },
    { linkedin = "https://linkedin.com/in/megaconfidence" },
]
